<?php
//Массив значений по умолчанию для канванса
$data_input = array
(
    'place_of_contract' => '[Город договора]',
    'date_of_contract' => '[Дата заключения]',
    'mark' => '[Марка машины]',
    'vin' => '[Идентификационный номер машины]',
    'reg_gov_number' => '[Гос. регистрационный знак машины]',
    'car_type' => '[Тип машины]',
    'category' => '[Категория]',
    'date_of_product' => '[Дата изготовления машины]',
    'engine_model' => '[Модель, номер двигателя]',
    'shassi' => '[Шасси]',
    'carcass' => '[Кузов]',
    'color_carcass' => '[Цвет кузова]',
    'other_parameters' => '[отсутствуют]',
    'additional_equip' => '[Дополнительное оборудование]',
    'serial_car' => '[Серия паспорта машины]',
    'number_of_serial_car' => '[Номер паспорта машины]',
    'bywho_serial_car' => '[Кем выдан паспорт]',
    'date_of_serial_car' => '[Дата выдачи паспорта серийного номера]',
    'firstside_requisites' => '[Реквизиты первой стороны]',
    'secondside_requisites' => '[Реквизиты второй стороны]',
    'type_of_contract' => 'gift',
    'type_of_giver' => 'physical',
    'type_of_taker' => 'physical',
    'vendor_surname' => '[Ф.',
    'vendor_name' => 'И.',
    'vendor_patronymic' => 'О. продавца]',
    'buyer_surname' => '[Ф.',
    'buyer_name' => 'И.',
    'buyer_patronymic' => 'О. покупателя]',
    'vendor_is_owner_car' => 'own_car',
    'buyer_is_owner_car' => 'own_car',
    'penalty' => '[не предусмотрена]',
    'vendor_phone' => '[отсутствует]',
    'vendor_law_phone' => '[отсутствует]',
    'vendor_ind_phone' => '[отсутствует]',
    'buyer_phone' => '[отсутствует]',
    'buyer_law_phone' => '[отсутствует]',
    'buyer_ind_phone' => '[отсутствует]',
);
