<?php
    //Массив значений по умолчанию для канванса
$data_input = array
(
    'place_of_contract' => '[Город договора]',
    'date_of_contract' => date("Y-m-d"),
    'mark' => '[Марка машины]',
    'vin' => '[Идентификационный номер машины]',
    'reg_gov_number' => '[Гос. регистрационный знак машины]',
    'car_type' => '[Тип машины]',
    'category' => '[Категория]',
    'date_of_product' => date("Y-m-d"),
    'engine_model' => '[Модель, номер двигателя]',
    'shassi' => '[Шасси]',
    'carcass' => '[Кузов]',
    'color_carcass' => '[Цвет кузова]',
    'other_parameters' => '[Иные индивидуальные признаки]',
    'additional_devices_array' => array('[Дополнительное оборудование]'),
    'serial_car' => '[Серия паспорта машины]',
    'number_of_serial_car' => '[Номер паспорта машины]',
    'bywho_serial_car' => '[Кем выдан паспорт]',
    'date_of_serial_car' => date("Y-m-d"),
    'car_allstatus' => '[Состояние машины]',
    'maintenance_date' => date("Y-m-d"),
    'maintenance_bywho' => '[Кем проведенно обсдуживание]',
    'defects' => '[Дефекты]',
    'features' => '[Особенности]',
    'price_car' => '[Цена ТС]',
    'price_str' => '[Цена в буквах]',
    'currency' => '[Валюта]',
    'payment_date' => '[Сроки оплаты]',
    'documents' => array('[Документы]'),
    'accessories' => array('[Аксесуары]'),
    'penalty' => '[Размер штрафа]',
    'firstside_requisites' => '[Реквизиты первой стороны]',
    'secondside_requisites' => '[Реквизиты второй стороны]',
    'type_of_contract' => 'buy_sell',
    'type_of_giver' => 'physical',
    'type_of_taker' => 'physical',
    'vendor_surname' => '[Ф.',
    'vendor_name' => 'И.',
    'vendor_patronymic' => 'О. продавца]',
    'buyer_surname' => '[Ф.',
    'buyer_name' => 'И.',
    'buyer_patronymic' => 'О. покупателя]',
    'vendor_is_owner_car' => 'own_car',
    'buyer_is_owner_car' => 'own_car',
    'penalty' => '[Размер процента]',

);